### PR TITLE
skip cleanup of not_used.txt in CI context

### PR DESCRIPTION
**Pull request by fbenke-pik**
This PR skips any adjustments of `not_used.txt` when running when codeCheck is executed as part of the Github Actions.

See also: https://github.com/pik-piam/gms/issues/85

### CODE REVIEW

**Comment by orichters** [comment]
@fbenke-pik: I think a better way would be to do all sorts of removals only in `interactive = TRUE` mode. That excludes codeCheck in github actions anyway, but we can also switch that simply off in the tests and we are some steps further.

**Comment by fbenke-pik** [comment]
Will probably be closed in favour of https://github.com/pik-piam/gms/pull/91

**Comment by orichters** [comment]
I would still merge this one as well. I think github actions should not tinker with the sources in order to satisfy codeCheck. Like this, you also have a good test whether people actually commit and push the changes `make check-fix` has applied.

**Review by orichters — APPROVED** [review]

**Comment by tscheypidi** [comment]
Why not link this to the `interactive` argument as this one is specifically targeted at fixing issues? `interactive = TRUE` try to live fix some issues, `interactive = FALSE` no issue fixing?

**Comment by fbenke-pik** [comment]
Right, Oliver probably will do exactly that in the near future.

**Comment by orichters** [comment]
Closed in favor of https://github.com/pik-piam/gms/pull/92

**Pull request closed without merging**
